# shutupapple - Apple telemetry sinkhole for OpenWrt
address=/metrics.apple.com/0.0.0.0
address=/metrics.icloud.com/0.0.0.0
address=/xp.apple.com/0.0.0.0
address=/securemetrics.apple.com/0.0.0.0
address=/supportmetrics.apple.com/0.0.0.0
address=/diagnosics.apple.com/0.0.0.0
address=/idiagnostics.apple.com/0.0.0.0
address=/iphonesubmissions.apple.com/0.0.0.0
address=/radarsubmissions.apple.com/0.0.0.0
address=/bookkeeper.itunes.apple.com/0.0.0.0
address=/weather-analytics-events.apple.com/0.0.0.0
address=/stats.apple.com/0.0.0.0
address=/pancake.apple.com/0.0.0.0
address=/feedbackws.icloud.com/0.0.0.0
address=/api-glb-ause.smoot.apple.com/0.0.0.0
address=/smoot.apple.com/0.0.0.0
address=/gsp-ssl.ls.apple.com/0.0.0.0
address=/gsp10-ssl.ls.apple.com/0.0.0.0
address=/gsp64-ssl.ls.apple.com/0.0.0.0
address=/gs-loc.apple.com/0.0.0.0
address=/iadsdk.apple.com/0.0.0.0
address=/tr.iadsdk.apple.com/0.0.0.0
address=/iad.apple.com/0.0.0.0
address=/advertising.apple.com/0.0.0.0
address=/banners.itunes.apple.com/0.0.0.0
address=/api.smoot.apple.com/0.0.0.0
address=/configuration.ls.apple.com/0.0.0.0
address=/swallow.apple.com/0.0.0.0
address=/xp.icloud.com/0.0.0.0
address=/experiment.apple.com/0.0.0.0
address=/push.apple.com/0.0.0.0
address=/courier.push.apple.com/0.0.0.0
address=/courier1.push.apple.com/0.0.0.0
address=/courier2.push.apple.com/0.0.0.0
